In [1]:
import numpy as np
import torch

# Using Numpy

In [8]:
#Create random matrices
A= np.random.rand(3,4)
B= np.random.rand(4,5)
C= np.random.rand(3,7)

#try some multiplications
print(f"{np.round(A@B ,2)}\n") #A@B in python @ multiplies matrices
#print(f"{np.round(A@C ,2)}\n")  # error: inner dimensions 4 and 3 don't match
#print(f"{np.round(B@C ,2)}\n")  # error: inner dimensions 5 and 3 don't match
print(f"{np.round(C.T@A, 2)}")

[[0.69 0.65 0.74 1.04 0.86]
 [0.91 0.71 0.83 1.22 0.91]
 [0.97 1.15 1.24 1.92 1.75]]

[[0.71 0.6  1.03 0.45]
 [0.97 0.77 1.31 0.63]
 [1.26 0.82 1.57 0.96]
 [0.34 0.44 0.64 0.12]
 [0.82 0.67 1.29 0.59]
 [1.01 0.7  1.01 0.62]
 [1.09 0.67 1.25 0.82]]


# Using pytorch

In [14]:
#Create random matrices
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor(C1, dtype = torch.float) #Convert to tensor

print(f"{np.round(A@B ,2)}\n")   # valid: (3×4) @ (4×5) = (3×5)
#print(f"{np.round(A@B.T ,2)}\n") # error: inner dimensions 4 and 5 don't match
print(f"{np.round(A@C1 ,2)}\n")  # works, but warning: mixing Torch (A) and NumPy (C1)
print(f"{np.round(A@C2 ,2)}\n")  # valid: (3×4) @ (4×7) = (3×7), both Torch tensors


tensor([[-0.5500,  0.3200, -0.6600, -3.1000, -1.1100],
        [ 0.1100,  0.6000,  0.1900, -0.5100, -0.8200],
        [ 0.5000, -0.8900,  0.6600, -0.0400,  0.3400]])

tensor([[-0.1200, -0.7500,  1.6300,  0.6200,  1.7900,  1.0700,  0.4300],
        [-2.5100, -1.1500,  0.0000, -0.4500, -1.8300, -1.8100,  1.0500],
        [ 0.3800,  1.0600,  0.2800, -0.0600,  1.6200,  1.1300, -0.0700]],
       dtype=torch.float64)

tensor([[-0.1200, -0.7500,  1.6300,  0.6200,  1.7900,  1.0700,  0.4300],
        [-2.5100, -1.1500,  0.0000, -0.4500, -1.8300, -1.8100,  1.0500],
        [ 0.3800,  1.0600,  0.2800, -0.0600,  1.6200,  1.1300, -0.0700]])



C:\Users\johnp\AppData\Local\Temp\ipykernel_7144\1435267618.py:9: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(f"{np.round(A@C1 ,2)}\n")  # works, but warning: mixing Torch (A) and NumPy (C1)
