In [1]:
import numpy as np
import torch
import torch.nn as nn

In [8]:
#Create a vector
v = np.array([1,2,40,-3])

#find and report the maximum and minimum values
minval = np.min(v)
maxval = np.max(v)

print(f"Min, Max: {minval},{maxval}\n")

#argmin and argmax
minidx = np.argmin(v)
maxidx = np.argmax(v)

print(f"Argmin, Argmax: {minidx},{maxidx}\n")
print(f"Argmin, Argmax: {minidx + 1},{maxidx + 1}\n")

Min, Max: -3,40

Argmin, Argmax: 3,2

Argmin, Argmax: 4,3



In [18]:
#Repeat for matrix
M = np.array([[0,1,10],[20,8,5]])
print(M)
minvals1 = np.min(M) # min from entire matrix
minvals2 = np.min(M, axis=0) # min of each column 
minvals3 = np.min(M, axis=1) # min of each rows

print(minvals1) 
print(minvals2)
print(minvals3)

[[ 0  1 10]
 [20  8  5]]
0
[0 1 5]
[0 5]


In [19]:
#for the argmin
minidx1 = np.argmin(M) # argmin from entire matrix
minidx2 = np.argmin(M, axis=0) # argmin of each column 
minidx3 = np.argmin(M, axis=1) # argmin of each rows

print(minidx1) 
print(minidx2)
print(minidx3)

0
[0 0 1]
[0 2]


# For pytorch

In [20]:
# create a vector
v = torch.tensor([ 1,40,2,-3 ])

# find and report the maximum and minimum values
minval = torch.min(v)
maxval = torch.max(v)

print('Min,max: %g,%g' %(minval,maxval) )


# now for the argmin/max
minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print('Min,max indices: %g,%g' %(minidx,maxidx) ), print(' ')

# confirm
print(f'Min val is { v[minidx] }, max val is { v[maxidx] }')

Min,max: -3,40
Min,max indices: 3,1
 
Min val is -3, max val is 40


In [27]:
# repeat with matrix
M = torch.tensor([ [0,1,10], [20,8,5] ])
print(M), print(' ')

# various minima in this matrix!
min1 = torch.min(M)        # minimum from ENTIRE matrix
min2 = torch.min(M,axis=0) # minimum of each column (across rows)
min3 = torch.min(M,axis=1) # minimum of each row (across columns)

# print them out
print(min1), print(' ')
print(min2), print(' ')
print(min2.values)
print(min2.indices)
print(" ")
print(min3), print(' ')
print(min3.values)
print(min3.indices)

tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
 
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
 
tensor([0, 1, 5])
tensor([0, 0, 1])
 
torch.return_types.min(
values=tensor([0, 5]),
indices=tensor([0, 2]))
 
tensor([0, 5])
tensor([0, 2])
