In [1]:
import numpy as np
import torch

In [7]:
np.random.randn(5)

array([ 2.171257  ,  1.15231025, -1.81881234, -0.13804934,  0.53983961])

In [13]:
#Global Seeding
np.random.seed(17)
print(np.random.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


# New seed Mechanism

In [19]:
#Local Seeding
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(20918346)
print(randseed1.randn(5))
print(randseed2.randn(5))
print(randseed1.randn(5))
print(randseed2.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.07329789 -0.36874908 -0.41738116 -0.40722137 -1.73066466]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 0.28611648  0.00332193  0.96611686 -0.87560284  2.53312597]
[ 0.13126776 -1.21256024  0.15999085 -0.75522304  0.34989599]


# Pytorch

In [20]:
torch.randn(5)

tensor([ 0.4341,  0.0367, -0.6697,  1.1337, -1.2297])

In [24]:
torch.manual_seed(17)
print(torch.randn(5))

torch.randn(5)

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])


tensor([-0.6124, -1.1835, -1.4831,  1.8004,  0.0096])