In [2]:
import numpy as np
import torch

# Transposing a Vector using numpy

In [ ]:
#Create a vector
nv = np.array([[1,2,3,4]]) #first square bracket indicates that we want to input an array, second array indicates the first row
print(f"{nv} \n")

#Transposing a vector
print(f"{nv.T}\n") #or np.tranpose(nv)

#Transpose the transposed vector
nvt = nv.T
print(f"{nvt.T}\n")

# Transposing a Matrix using numpy

In [19]:
#Create a matrix
nm = np.array([
        [1,0,2,5,-2],
        [5,6,8,3,0]
        ])
print(f"{nm}\n")

#Transposing a matrix
print(f"{nm.T}\n") #or np.tranpose(nm)

#Tranpose the transposed matrix
nmt = nm.T
print(nmt.T)

[[ 1  0  2  5 -2]
 [ 5  6  8  3  0]]

[[ 1  5]
 [ 0  6]
 [ 2  8]
 [ 5  3]
 [-2  0]]

[[ 1  0  2  5 -2]
 [ 5  6  8  3  0]]


# Transposing a Vector using pytorch

In [25]:
#Create a vector
tv = torch.tensor([[1,2,3,4]])
print(f"{tv}\n")

#Transpose a vector
print(f"{tv.T}\n")

#Transpose the transposed vector
tvt = tv.T
print(f"{tvt.T}\n")

tensor([[1, 2, 3, 4]])

tensor([[1],
        [2],
        [3],
        [4]])

tensor([[1, 2, 3, 4]])



# Transposing a Matrix using pytorch

In [27]:
#Create a matrix
tm = torch.tensor([
    [1,2,3,4],
    [5,6,7,8]
    ])
print(f"{tm}\n")

#Transpose a vector
print(f"{tm.T}\n")

#Transpose the transposed vector
tmt = tm.T
print(f"{tmt.T}\n")

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

